### ISSUE TITLE
[Tracker] List of Razor items to be consumed by tooling.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1626]
Today the Visual Studio components utilize MEF exports/imports to interact with our VisualStudio.LanguageServices.Razor utilities. Once those VS components move to utilize the CodeAnalysis.Razor services (copies but updated) we'll need to work with them to consume the following changes:

- [x] https://github.com/aspnet/Razor/issues/1572 - Shelveset `ajbaaska-1572`
- [x] [Let Razor handle editing loop](https://github.com/aspnet/Razor/issues/1630) - Shelveset `NTM-VSRazorParser`
- [x] [Add integration tests for directive completion](https://github.com/aspnet/Razor/issues/1742) - Shelveset `NTM-RazorDirectiveCompletionTests`
