### ISSUE TITLE
Razor Startup Time investigation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1741]
We've collected some data recently that shows that Razor is about 35% of the time to first request for an MVC starter site. This item is a meta-item tracking our investigations and investments

----------------

#### Data
Of that time the rough breakdown is:
5% misc overhead
24% emitting assembly
32% tag helper discovery
35% expression rewriter
4% razor parsing and codegen

#### Conclusions

JIT and initialization is the biggest factor by far. JIT is approx 40% of process CPU time. Specifically Roslyn+ValueTypes+ImmutableCollections is the worst case for crossgen and results in a lot of runtime JIT happening for things that crossgen can't deal with.

We know that JIT is significant because subsequent compilations after the first are orders of magnitude faster and are already measured in the test.

We have some low-hanging fruit in Razor/MVC.

The 'core' Razor engine only accounts for 4% of the view compilation time. Most of our general Razor features are not a candidate for optimization.

GC isn't really a factor. The process doesn't allocate much. 

#### Investments

- [ ] Optimize TagHelper discovery #1737
- [ ] Optimize Expression Rewriter #1738
- [ ] Investigate Pre-Loading Roslyn #1739
- [ ] Big Rock: Eliminate Roslyn from Inner Loop Startup #1740

**Comment by Yves57** [comment]
@rynowak For curiosity or to get ideas, is it possible for you to share the profiling results?

**Comment by rynowak** [comment]
Sure

**Comment by rynowak** [comment]
BTW @Yves57 - we didn't forget about you... We ran #1738 and #1739 in the VS perf lab earlier this week, hoping to find some time to do analysis on the results in the next day or so.

**Comment by Yves57** [comment]
@rynowak no problem! And thank you for the time that you spend to communicate.

**Comment by rynowak** [comment]
Apologies, I never did end up getting profiles for these. 

From memory, here are the results:
- Preloading Roslyn - the impact wasn't clear, it was below the level of noise in the runs (which include VS)
- Removing expression rewriter had a big impact (800ms)

We're pivoting to a model where Razor is primarily used at build time, and we've been focused on that. We do intend to do the pre-load of Roslyn when we get a chance, that will help, because the first view we run will likely be precompiled. This way the warmup will happen in the background, and will help the first time you edit something after the site is started.
