### ISSUE TITLE
Meta: Replace MvcTemplateEngine

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1828]
Living list of things a part of this issue.

- [x] Add contracts for RazorProjectEngine creation
- [ ] Make MVC registrations work with RazorProjectEngine
- [x] Lift RazorEngineBuilderExtension concepts onto RazorProjectEngineBuilder

**Comment by rynowak** [comment]
Related to built-time-razor, because we're hard coding more MVC-isms in yet another place.

**Comment by NTaylorMullen** [comment]
- [ ] Add contracts for `RazorProjectEngine` creation
- [ ] Make MVC registrations work with `RazorProjectEngine`
- [ ] Lift `RazorEngineBuilderExtension` concepts onto `RazorProjectEngineBuilder`

**Comment by NTaylorMullen** [comment]
59f2cf8e66daec67c90c9b4294d2cf5ba7f7230a
