### ISSUE TITLE
Meta: Turn Razor MSBuild support into an SDK

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1892]
The design of this looks roughly like:

`Microsoft.Net.Razor.Sdk` - contains the compilation (CSC) targets as well as the targets and properties that hook into the build lifecycle. This SDK defines the primary properties that users will want to configure. This package versions with the SDK and moves slowly.

`Microsoft.AspNetCore.Razor.Xyz` - contains the actual tools used for tag helper discovery and code generation, as well as any version-specific settings. This package moves with the runtime and can version/change quickly. There's a stable contract between this package and the main SDK. Once things stabilize, functionality can move from here into the SDK.

`Microsoft.AspNetCore.Mvc.Xyz` - contains the 'targeting pack' for MVC. This package moves with the runtime and can version/change quickly.

---

We need to cobble what we have into this shape for preview 2 and then get the `Microsoft.Net.Razor.Sdk` package into the CLI Build.

---

Requirements:
- [x] Relayer the 2.1.0-preview1 stuff into SDK (see description above)
- [x] Insert into CLI for 2.1.0-preview2
- [x] Flesh out configuration for Razor (version, plugins, more?)
- [x] Take over functionality from WebSDK as needed
- [x] Define a capability for Razor (that our tooling understands)
- [x] Build a plugin system for CLI tool (rzc)
- [x] Expose version and plugin information for VS
- [ ] Docs (minimal)

**Comment by pranavkm** [comment]
## Take over functionality from WebSDK as needed

Things that already exist:

* `RazorCompileToolset`
* `ResolvedRazorCompileToolset`
* `MvcRazorCompileOnPublish`
* `<Content Include="**\*.cshtml" CopyToPublishDirectory="PreserveNewest" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);wwwroot\**" />` <-- Maybe

Additional stuff to add 
* `ProjectCapability`

Anything else I'm missing?

**Comment by rynowak** [comment]
That sounds right to me overall.  I think the content itemgroup needs discussion.

**Comment by rynowak** [comment]
I checked off a few boxes that I've done.

**Comment by rynowak** [comment]
Unassigning others because they've done their part 👍

**Comment by rynowak** [comment]
Closing this as done. We will use https://github.com/aspnet/Razor/issues/2119 to track docs.
