### ISSUE TITLE
Meta: Add Razor build server

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1921]
Checklist:

- [x] Get tag helper discovery and code generation working end to end (off by default) (https://github.com/aspnet/Razor/issues/1943)
- [x] Resolve how many/what tools we have (https://github.com/aspnet/Razor/issues/1953)
- [x] Server timeout after a certain time
- [x] Server should support different Razor toolset versions at the same time (https://github.com/aspnet/Razor/pull/2058)
- [x] Include more data as part of the inputs to the server
- [x] Logging cleanup (https://github.com/aspnet/Razor/issues/1954)
- [x] Integrate in to the build
- [x] Turn it on by default when it is in good shape (https://github.com/aspnet/Razor/pull/2131)
- [x] Tests (https://github.com/aspnet/Razor/issues/1958)
- [x] Get automated perf measurements working

**Comment by ajaybhargavb** [comment]
Perf data when the server is already running,
**Target Performance Summary:**
        0 ms  PrepareResourceNames                       1 calls
        0 ms  BeforeResGen                               1 calls
        0 ms  AfterBuild                                 1 calls
        0 ms  ResolvePackageDependenciesForBuild         1 calls
        0 ms  SetWin32ManifestProperties                 1 calls
        0 ms  AfterRebuild                               1 calls
        0 ms  BeforeBuild                                1 calls
        0 ms  Clean                                      1 calls
        0 ms  BeforeCompile                              1 calls
        0 ms  PrepareForRun                              1 calls
        0 ms  AfterClean                                 1 calls
        0 ms  PrepareProjectReferences                   1 calls
        0 ms  PrepareResources                           1 calls
        0 ms  CoreBuild                                  1 calls
        0 ms  GenerateAssemblyInfo                       1 calls
        0 ms  BeforeClean                                1 calls
        0 ms  GetFrameworkPaths                          1 calls
        0 ms  GetReferenceAssemblyPaths                  1 calls
        0 ms  RazorGenerate                              1 calls
        0 ms  AfterResolveReferences                     1 calls
        0 ms  BeforeRebuild                              1 calls
        0 ms  ResGen                                     1 calls
        0 ms  CreateCustomManifestResourceNames          1 calls
        0 ms  Compile                                    1 calls
        0 ms  _CopySourceItemsToOutputDirectory          1 calls
        0 ms  RazorCompile                               1 calls
        0 ms  CreateSatelliteAssemblies                  1 calls
        0 ms  AfterResGen                                1 calls
        0 ms  BeforeResolveReferences                    1 calls
        0 ms  Rebuild                                    1 calls
        0 ms  AfterCompile                               1 calls
        0 ms  BuildOnlySettings                          1 calls
        0 ms  ResolveLockFileAnalyzers                   1 calls
        0 ms  _GenerateProjectRestoreGraph               1 calls
        0 ms  Build                                      1 calls
        0 ms  _CheckForUnsupportedSelfContained          1 calls
        0 ms  _GenerateRestoreGraphProjectEntry          1 calls
        0 ms  _DefaultMicrosoftNETPlatformLibrary        1 calls
        0 ms  _SetTargetFrameworkMonikerAttribute        1 calls
        0 ms  IncludeTransitiveProjectReferences         1 calls
        0 ms  CleanPublishFolder                         1 calls
        0 ms  ExpandSDKReferences                        1 calls
        0 ms  CollectPackageReferences                   2 calls
        0 ms  GetTargetPath                              1 calls
        0 ms  ResolveSDKReferences                       1 calls
        0 ms  CleanReferencedProjects                    1 calls
        0 ms  _GetRestoreProjectStyle                    2 calls
        0 ms  ComputeDependencyFileCompilerOptions       1 calls
        0 ms  _ComputeActiveTFMPackageDependencies       1 calls
        0 ms  _GetRestoreTargetFrameworksAsItems         1 calls
        0 ms  _IsProjectRestoreSupported                 1 calls
        0 ms  _GetRestoreSettingsPerFramework            1 calls
        0 ms  _GetRestoreSettingsOverrides               1 calls
        0 ms  CheckForImplicitPackageReferenceOverridesBeforeRestore   2 calls
        0 ms  _SplitProjectReferencesByFileExistence     1 calls
        0 ms  _GetProjectJsonPath                        2 calls
        0 ms  ResolveReferences                          1 calls
        0 ms  _CheckForUnsupportedNETCoreVersion         4 calls
        0 ms  _ComputeLockFileFrameworks                 1 calls
        0 ms  GetAssemblyAttributes                      1 calls
        0 ms  _ComputeTransitiveProjectReferences        1 calls
        0 ms  _CopyReferenceOnlyAssembliesForBuild       1 calls
        0 ms  _ComputeLockFileAnalyzers                  1 calls
        0 ms  _GenerateCompileInputs                     1 calls
        0 ms  CoreResGen                                 1 calls
        0 ms  _RazorGetCopyToOutputDirectoryItems        1 calls
        0 ms  _ComputeNETCoreBuildOutputFiles            1 calls
        0 ms  _GenerateRestoreProjectPathWalk            1 calls
        0 ms  _CheckForCompileOutputs                    1 calls
        0 ms  _GenerateRestoreSpecs                      1 calls
        0 ms  _ComputeActiveTFMFileDependencies          1 calls
        0 ms  _ComputeTFMOnlyFileDependencies            1 calls
        1 ms  GetCopyToOutputDirectoryItems              1 calls
        1 ms  GetAssemblyVersion                         1 calls
        1 ms  _GenerateSatelliteAssemblyInputs           1 calls
        1 ms  _ComputeReferenceAssemblies                1 calls
        1 ms  RazorResolveGenerateInputs                 1 calls
        1 ms  _GenerateRestoreProjectSpec                1 calls
        1 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
        1 ms  _GenerateRestoreProjectPathItemsPerFramework   1 calls
        1 ms  _RazorResolveReferences                    1 calls
        1 ms  _CollectTargetFrameworkForTelemetry        1 calls
        1 ms  SplitResourcesByCulture                    1 calls
        1 ms  GenerateTargetFrameworkMonikerAttribute    1 calls
        1 ms  AssignTargetPaths                          1 calls
        1 ms  GetTargetPathWithTargetPlatformMoniker     1 calls
        1 ms  CheckForDuplicateItems                     1 calls
        1 ms  _SetEmbeddedWin32ManifestProperties        1 calls
        2 ms  CreateGeneratedAssemblyInfoInputsCacheFile   1 calls
        2 ms  _GetRestoreTargetFrameworksOutput          1 calls
        2 ms  ReportAssetsLogMessages                    1 calls
        2 ms  _GetProjectReferenceTargetFrameworkProperties   1 calls
        3 ms  CoreGenerateAssemblyInfo                   1 calls
        3 ms  IncrementalClean                           1 calls
        3 ms  PrepareForBuild                            1 calls
        3 ms  _ResolveRazorCoreGenerateInputs            1 calls
        4 ms  _GenerateCompileDependencyCache            1 calls
        4 ms  _ComputeLockFileReferences                 1 calls
        5 ms  _CleanGetCurrentAndPriorFileWrites         1 calls
        5 ms  _HandlePackageFileConflicts                1 calls
        5 ms  _GenerateProjectRestoreGraphPerFramework   1 calls
        5 ms  CheckForImplicitPackageReferenceOverrides   3 calls
        6 ms  CopyFilesToOutputDirectory                 1 calls
        7 ms  _RazorCopyFilesToOutputDirectory           1 calls
        7 ms  _GenerateRestoreDependencies               1 calls
        7 ms  _ComputeLockFileCopyLocal                  1 calls
        7 ms  _GenerateDotnetCliToolReferenceSpecs       1 calls
        7 ms  ResolveLockFileReferences                  1 calls
        8 ms  RunProduceContentAssets                    1 calls
        9 ms  _LoadRestoreGraphEntryPoints               1 calls
       13 ms  RunResolvePackageDependencies              1 calls
       17 ms  FindReferenceAssembliesForReferences       1 calls
       20 ms  CoreClean                                  1 calls
       23 ms  _CopyFilesMarkedCopyLocal                  1 calls
       23 ms  _GetRestoreSettings                        1 calls
       38 ms  ResolveProjectReferences                   1 calls
       42 ms  _GenerateRestoreProjectPathItems           1 calls
       42 ms  _GenerateRestoreGraph                      1 calls
       45 ms  GenerateBuildDependencyFile                1 calls
       56 ms  _GetAllRestoreProjectPathItems             1 calls
       63 ms  GenerateBuildRuntimeConfigurationFiles     1 calls
      ** 93 ms  _RazorResolveTagHelpers                    1 calls**
      116 ms  _FilterRestoreGraphProjectInputItems       1 calls
      162 ms  Restore                                    1 calls
      225 ms  ResolveAssemblyReferences                  1 calls
      768 ms  RazorCoreGenerate                          1 calls
      977 ms  CoreCompile                                1 calls
     1218 ms  RazorCoreCompile                           1 calls

Task Performance Summary:
        0 ms  AssignCulture                              1 calls
        0 ms  GetAssemblyVersion                         1 calls
        0 ms  FindAppConfigFile                          1 calls
        0 ms  Telemetry                                  1 calls
        0 ms  GetRestoreProjectReferencesTask            1 calls
        1 ms  CheckForTargetInAssetsFile                 1 calls
        1 ms  GetFrameworkPath                           1 calls
        1 ms  AssignTargetPath                           5 calls
        1 ms  ConvertToAbsolutePath                      3 calls
        1 ms  Hash                                       3 calls
        1 ms  Message                                    7 calls
        1 ms  CheckForDuplicateItems                     3 calls
        1 ms  ReadLinesFromFile                          2 calls
        2 ms  GetProjectTargetFrameworksTask             1 calls
        2 ms  ReportAssetsLogMessages                    1 calls
        2 ms  FindUnderPath                              7 calls
        2 ms  WriteCodeFragment                          1 calls
        3 ms  WarnForInvalidProjectsTask                 1 calls
        3 ms  CheckForImplicitPackageReferenceOverrides   3 calls
        3 ms  ResolvePackageFileConflicts                1 calls
        4 ms  RemoveDuplicates                           8 calls
        4 ms  GetRestorePackageReferencesTask            1 calls
        4 ms  MakeDir                                    4 calls
        5 ms  RemoveDir                                  1 calls
        7 ms  Touch                                      2 calls
        7 ms  GetRestoreDotnetCliToolsTask               1 calls
        7 ms  ProduceContentAssets                       1 calls
       10 ms  JoinItems                                  8 calls
       10 ms  WriteLinesToFile                           5 calls
       12 ms  ResolvePackageDependencies                 1 calls
       17 ms  Delete                                     3 calls
       21 ms  GetRestoreSettingsTask                     1 calls
       33 ms  Copy                                       6 calls
       44 ms  GenerateDepsFile                           1 calls
       62 ms  GenerateRuntimeConfigurationFiles          1 calls
       **85 ms  RazorTagHelper                             1 calls**
      161 ms  RestoreTask                                1 calls
      224 ms  ResolveAssemblyReference                   1 calls
      242 ms  MsBuild                                   10 calls
      759 ms  RazorGenerate                              1 calls
     2191 ms  Csc                                        2 calls

**Comment by ajaybhargavb** [comment]
This is now on by default. Closing this issue.
