### ISSUE TITLE
Razor parser improvements

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2508]
As a follow-up to #2263 and as a prerequisite for a bunch of future Razor improvements, we want to have our current Razor parser to have a deeper understanding of HTML. Here is a detailed description of what this will enable us to do https://github.com/aspnet/Razor/issues/2211#issue-307854491.

**Comment by ajaybhargavb** [comment]
Checklist:

- [x] Import and adapt the Syntax tree infrastructure from Roslyn (#2522) [Cost: **M**]
- [x] Rewrite the Tokenizer layer (#2540) [Cost: **S**]
- [x] Add a way to auto generate node classes and other boilerplate based on the Syntax (#2550) [Cost: **S**]
- [ ] Rewrite CSharp parser (In progress) [Cost: **M**]
- [ ] Rewrite Html parser (In progress) [Cost: **M**]
- [ ] Rewrite the classified span generation logic (In progress) [Cost: **S**]
- [ ] Rewrite the Tag helper parsing layer
- [ ] Rewrite other syntax tree visitors like WhitespaceRewriter, ConditionalAttributeCollapser etc
- [ ] Rewrite the IR layer to use the new syntax tree
- [ ] React and update parser test infrastructure (In progress) [Cost: **S**]
- [ ] Regenerate the parser test baselines with the new syntax tree and review them thoroughly for accuracy
- [ ] Add unit tests for the new syntax tree infrastructure
- [ ] React and update all other dependent tests
